package io.arct.dialoguetree.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int ActionSet = 1;
  public static final int ActionSetReference = 2;
  public static final int Dialogue = 3;
  public static final int DialogueReference = 4;
  public static final int DialogueTree = 5;
  public static final int EntryDialogue = 6;
  public static final int ExitAction = 7;
  public static final int IfAction = 8;
  public static final int Modifier = 9;
  public static final int ModifierReference = 10;
  public static final int Option = 11;
  public static final int OptionsAction = 12;
  public static final int Participant = 13;
  public static final int ParticipantReference = 14;
  public static final int Property = 15;
  public static final int PropertyReference = 16;
  public static final int RandomAction = 17;
  public static final int ReturnAction = 18;
  public static final int StructureDumper = 19;
  public static final int Text = 20;
  public static final int TextModifier = 21;
  public static final int ToActionSetAction = 22;
  public static final int ToDialogueAction = 23;
  public static final int ToEntryAction = 24;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x200ef616249d4ed7L, 0x9810cbdeaf100067L);
    builder.put(0x56f13ba7056d3ef7L, Action);
    builder.put(0x56f13ba7058b1644L, ActionSet);
    builder.put(0x56f13ba7059b2ca7L, ActionSetReference);
    builder.put(0x56f13ba7056a71c4L, Dialogue);
    builder.put(0x56f13ba7059b2c96L, DialogueReference);
    builder.put(0x56f13ba705693edcL, DialogueTree);
    builder.put(0x56f13ba7056be8d9L, EntryDialogue);
    builder.put(0x56f13ba7056d3f19L, ExitAction);
    builder.put(0x56f13ba705913a99L, IfAction);
    builder.put(0x823c998d80d4483L, Modifier);
    builder.put(0x823c998d80d4484L, ModifierReference);
    builder.put(0x56f13ba7056d89ffL, Option);
    builder.put(0x56f13ba7056d3efaL, OptionsAction);
    builder.put(0x812480f55445d42L, Participant);
    builder.put(0x812480f55445d45L, ParticipantReference);
    builder.put(0x56f13ba70593b1ceL, Property);
    builder.put(0x56f13ba7059b2caaL, PropertyReference);
    builder.put(0x812480f5549560cL, RandomAction);
    builder.put(0x56f13ba7056e10b4L, ReturnAction);
    builder.put(0x56f13ba7056fbc86L, StructureDumper);
    builder.put(0x56f13ba7056ae042L, Text);
    builder.put(0x823c998d80bca69L, TextModifier);
    builder.put(0x56f13ba7058bb408L, ToActionSetAction);
    builder.put(0x56f13ba7056d3f16L, ToDialogueAction);
    builder.put(0x56f13ba7056e824dL, ToEntryAction);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
