package io.arct.dialoguetree.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myDialogueTree__BehaviorDescriptor = new DialogueTree__BehaviorDescriptor();
  private final BHDescriptor myStructureDumper__BehaviorDescriptor = new StructureDumper__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myDialogueTree__BehaviorDescriptor;
      case 1:
        return myStructureDumper__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x200ef616249d4ed7L, 0x9810cbdeaf100067L, 0x56f13ba705693edcL), MetaIdFactory.conceptId(0x200ef616249d4ed7L, 0x9810cbdeaf100067L, 0x56f13ba7056fbc86L)).seal();
}
